//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ac_org
    {
        public int Id { get; set; }
        public string ac_name { get; set; }
        public string ac_address { get; set; }
        public float latitude { get; set; }
        public float longitude { get; set; }
        public string available_time { get; set; }
        public string ac_condition { get; set; }
    }
}
