//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laundry
    {
        public string Name { get; set; }
        public string Address { get; set; }
        public string Avai_days { get; set; }
        public string Timings { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
    }
}
