//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class feed_your_soulEntities : DbContext
    {
        public feed_your_soulEntities()
            : base("name=feed_your_soulEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ac_org> ac_org { get; set; }
        public virtual DbSet<food_org> food_org { get; set; }
        public virtual DbSet<Public_toilets> Public_toilets { get; set; }
        public virtual DbSet<Centrelink_Data> Centrelink_Data { get; set; }
        public virtual DbSet<Drinking_fountains> Drinking_fountains { get; set; }
        public virtual DbSet<Laundry> Laundries { get; set; }
    }
}
