//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Public_toilets
    {
        public string name { get; set; }
        public string female { get; set; }
        public string male { get; set; }
        public string wheelchair { get; set; }
        public string @operator { get; set; }
        public string baby_facil { get; set; }
        public double lat { get; set; }
        public double lon { get; set; }
    }
}
